---
- name: NAPALM Diff Checker and Install Config
  connection: ansible.netcommon.network_cli
  gather_facts: True
  hosts: routers
  tasks:

    - napalm_install_config:
          hostname: "{{ ansible_host }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          dev_os: "ios"
          config_file: "NAPALM/Backup_Configs/{{ inventory_hostname  }}/{{ inventory_hostname }}_bk.txt"
          commit_changes: False
          #Replace_config should always be set to false UNLESS you have a complete config file
          replace_config: True 
          get_diffs: True
          diff_file: "NAPALM/Diff_Outputs/{{ inventory_hostname }}_diff.txt"