---
- name: NAPALM Diff Checker and Install Config
  connection: ansible.netcommon.network_cli
  gather_facts: True
  hosts: routers

  tasks:
    - napalm_get_facts:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        dev_os: "ios"


    - napalm_validate:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        dev_os: "ios"
        validation_file: ./R1_compliance_rules.yml  # Specify the path to the validation file
      register: compliance_result
    
    - name: Print Compliance Result
      debug:
        var: compliance_result